### ISSUE TITLE
Make Last Extraction date stand out if extraction hasn't happened for a host for a "long" time

### ISSUE THREAD

**Issue by rosalyn** [rwang2010/crwltrckr#3]
I think not extracting from a host over 1 month is code "pink"; over 3 months is code "red". 

What I truly mean is, make the days/months ago font color pink if over 1 month, and red if over 3 months.

This is super low priority, but a nice-to-have.

**Comment by chip-factual** [comment]
We have code pinks in crwltrckr now! Crawls just got a lot more exciting.

![screen shot 2015-09-11 at 5 05 13 pm](https://cloud.githubusercontent.com/assets/10622520/9828768/4d277142-58a7-11e5-9fad-bb8e9b0d4f1c.png)
