### ISSUE TITLE
Display total # of cached pages for each crawl project

### ISSUE THREAD

**Issue by rosalyn** [rwang2010/crwltrckr#5]
Useful for getting a rough idea of the number of inputs we got for a country.

**Comment by chip-factual** [comment]
Added totals for all of the columns. I wasn't too sure what to put for last cached and last extraction, so I just put both the newest and the oldest dates. Might have to rethink that one. Let me know if you have any thoughts @rosalyn.

![screen shot 2015-09-25 at 5 06 58 pm](https://cloud.githubusercontent.com/assets/10622520/10114574/eb265a60-63a7-11e5-88d6-5ef0d86dad98.png)

**Comment by rosalyn** [comment]
In the row for 'totals', we can do `1 day to 2 months` for Last Cached, `15 days to 10 months` for Last Extraction. What you have now is fine, but if you want to update it... that's my thought!
