### ISSUE TITLE
Investigate efficiency of cache age mongo queries

### ISSUE THREAD

**Issue by chip-factual** [rwang2010/crwltrckr#7]
We've been seeing a lot of timeout errors recently when querying the pipelines mongodb. I'm worried that crwltrckr is only making things worse by adding its cache url age queries to the load mongo must handle.

As part of the pipelines crawl metrics initiative, we should investigate the efficiency of these input age queries, and consider either removing them completely, or adding them directly into pipelines.

cc @rosalyn @jazzyfresh-factual

**Comment by rosalyn** [comment]
Can you reference the lines to those inputs age queries?

**Comment by chip-factual** [comment]
Moved issue to pipelines repo.

**Comment by chip-factual** [comment]
Cache age charts have been moved to [feature/cache_age_charts](https://github.com/rwang2010/crwltrckr/compare/develop...feature/cache_age_charts) until we can find a more efficient implementation.

cc @ericlui
